// <auto-generated />
using System;
using Assignment2.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment2.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250411142144_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment2.Domain.Entities.Departments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Software Development"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accountant"
                        },
                        new
                        {
                            Id = 4,
                            Name = "HR"
                        });
                });

            modelBuilder.Entity("Assignment2.Domain.Entities.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("JoinedDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            JoinedDate = new DateOnly(2023, 5, 10),
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            JoinedDate = new DateOnly(2024, 1, 12),
                            Name = "Bob Smith"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            JoinedDate = new DateOnly(2023, 8, 5),
                            Name = "Charlie Lee"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 3,
                            JoinedDate = new DateOnly(2024, 2, 1),
                            Name = "Diana Patel"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 4,
                            JoinedDate = new DateOnly(2023, 9, 18),
                            Name = "Ethan Brown"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            JoinedDate = new DateOnly(2023, 11, 23),
                            Name = "Fiona Davis"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 2,
                            JoinedDate = new DateOnly(2024, 3, 2),
                            Name = "George Wang"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 3,
                            JoinedDate = new DateOnly(2024, 1, 25),
                            Name = "Hannah Kim"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 4,
                            JoinedDate = new DateOnly(2023, 7, 14),
                            Name = "Ian Walker"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 1,
                            JoinedDate = new DateOnly(2024, 2, 14),
                            Name = "Julia Martinez"
                        });
                });

            modelBuilder.Entity("Assignment2.Domain.Entities.ProjectEmployees", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("Enable")
                        .HasColumnType("bit");

                    b.HasKey("ProjectId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Project_Employee", (string)null);

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            EmployeeId = 1,
                            Enable = true
                        },
                        new
                        {
                            ProjectId = 1,
                            EmployeeId = 2,
                            Enable = true
                        },
                        new
                        {
                            ProjectId = 1,
                            EmployeeId = 3,
                            Enable = false
                        },
                        new
                        {
                            ProjectId = 2,
                            EmployeeId = 4,
                            Enable = true
                        },
                        new
                        {
                            ProjectId = 2,
                            EmployeeId = 5,
                            Enable = true
                        },
                        new
                        {
                            ProjectId = 2,
                            EmployeeId = 6,
                            Enable = false
                        },
                        new
                        {
                            ProjectId = 3,
                            EmployeeId = 7,
                            Enable = true
                        },
                        new
                        {
                            ProjectId = 3,
                            EmployeeId = 8,
                            Enable = false
                        },
                        new
                        {
                            ProjectId = 4,
                            EmployeeId = 1,
                            Enable = true
                        },
                        new
                        {
                            ProjectId = 4,
                            EmployeeId = 6,
                            Enable = true
                        },
                        new
                        {
                            ProjectId = 4,
                            EmployeeId = 9,
                            Enable = false
                        },
                        new
                        {
                            ProjectId = 5,
                            EmployeeId = 10,
                            Enable = true
                        },
                        new
                        {
                            ProjectId = 5,
                            EmployeeId = 3,
                            Enable = true
                        },
                        new
                        {
                            ProjectId = 5,
                            EmployeeId = 2,
                            Enable = false
                        },
                        new
                        {
                            ProjectId = 5,
                            EmployeeId = 5,
                            Enable = true
                        });
                });

            modelBuilder.Entity("Assignment2.Domain.Entities.Projects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Project Alpha"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Project Beta"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Project Gamma"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Project Delta"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Project Epsilon"
                        });
                });

            modelBuilder.Entity("Assignment2.Domain.Entities.Salaries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Salaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            Salary = 60000m
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            Salary = 70000m
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 3,
                            Salary = 65000m
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 4,
                            Salary = 80000m
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 5,
                            Salary = 75000m
                        },
                        new
                        {
                            Id = 6,
                            EmployeeId = 6,
                            Salary = 62000m
                        },
                        new
                        {
                            Id = 7,
                            EmployeeId = 7,
                            Salary = 72000m
                        },
                        new
                        {
                            Id = 8,
                            EmployeeId = 8,
                            Salary = 68000m
                        },
                        new
                        {
                            Id = 9,
                            EmployeeId = 9,
                            Salary = 64000m
                        },
                        new
                        {
                            Id = 10,
                            EmployeeId = 10,
                            Salary = 71000m
                        });
                });

            modelBuilder.Entity("Assignment2.Domain.Entities.Employees", b =>
                {
                    b.HasOne("Assignment2.Domain.Entities.Departments", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Assignment2.Domain.Entities.ProjectEmployees", b =>
                {
                    b.HasOne("Assignment2.Domain.Entities.Employees", "Employee")
                        .WithMany("ProjectEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment2.Domain.Entities.Projects", "Project")
                        .WithMany("ProjectEmployees")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Assignment2.Domain.Entities.Salaries", b =>
                {
                    b.HasOne("Assignment2.Domain.Entities.Employees", "Employee")
                        .WithOne("Salary")
                        .HasForeignKey("Assignment2.Domain.Entities.Salaries", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Assignment2.Domain.Entities.Departments", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Assignment2.Domain.Entities.Employees", b =>
                {
                    b.Navigation("ProjectEmployees");

                    b.Navigation("Salary");
                });

            modelBuilder.Entity("Assignment2.Domain.Entities.Projects", b =>
                {
                    b.Navigation("ProjectEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
